---

tasks:
  - init: sudo apt install python3 python3-pip
    command: |
      pip3 install ansible
      pip3 install ansible-builder


vscode:
  extensions:
    - redhat.vscode-yaml
    - ms-azuretools.vscode-docker
    - humao.rest-client
